CREATE TABLE IF NOT EXISTS user (
	user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	uuid CHAR(36) NOT NULL DEFAULT UUID() UNIQUE,
	roles VARCHAR(255) NOT NULL DEFAULT 'user',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_discord (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	discord_id BIGINT NOT NULL UNIQUE,
	access_token VARCHAR(255) NOT NULL,
	refresh_token VARCHAR(255) NOT NULL,
	FOREIGN KEY (user_id) REFERENCES user(user_id)
);