CREATE TABLE IF NOT EXISTS user (
	user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	uuid CHAR(36) NOT NULL DEFAULT UUID() UNIQUE,
	roles VARCHAR(255) NOT NULL DEFAULT 'user',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);